Makefile
ansible/inventory/group_vars/apps.yaml
ansible/playbooks/apps/author-dispatcher.yaml
ansible/playbooks/apps/author.yaml
ansible/playbooks/apps/dns-records.yaml
ansible/playbooks/apps/publish-dispatcher.yaml
cloudformation/apps/author-dispatcher.yaml
cloudformation/apps/author.yaml
cloudformation/apps/dns-records.yaml
cloudformation/apps/publish-dispatcher.yaml
examples/config_path/apps.yaml

Separate DNS Record creation into its own stacks, for scenario where we are not allowed to created DNS records.

Feature separate dns records

---

Makefile
README.md
ansible/playbooks/apps/author-dispatcher.yaml
ansible/playbooks/apps/author.yaml
ansible/playbooks/apps/chaos-monkey.yaml
ansible/playbooks/apps/dns-records.yaml
ansible/playbooks/apps/messaging.yaml
ansible/playbooks/apps/orchestrator.yaml
ansible/playbooks/apps/publish-dispatcher.yaml
ansible/playbooks/apps/publish.yaml
ansible/playbooks/apps/roles.yaml
ansible/playbooks/apps/security-groups.yaml
ansible/playbooks/network/bastion.yaml
ansible/playbooks/network/nat-gateway.yaml
ansible/playbooks/network/network.yaml
ansible/playbooks/network/vpc.yaml
scripts/create-aem-stacks.sh

adding stack existence check before deleting it
make sure failure exit code is captured instead of thrown away silently

Feature stack management improvement

---

ansible/inventory/group_vars/apps.yaml
ansible/playbooks/apps/author-dispatcher.yaml
ansible/playbooks/apps/author.yaml
ansible/playbooks/apps/chaos-monkey.yaml
ansible/playbooks/apps/orchestrator.yaml
ansible/playbooks/apps/publish-dispatcher.yaml
ansible/playbooks/apps/publish.yaml
cloudformation/apps/author-dispatcher.yaml
cloudformation/apps/author.yaml
cloudformation/apps/chaos-monkey.yaml
cloudformation/apps/orchestrator.yaml
cloudformation/apps/publish-dispatcher.yaml
cloudformation/apps/publish.yaml
scripts/create-aem-stacks.sh

Feature parameterize ebs vol size

---

ansible/playbooks/apps/chaos-monkey.yaml
cloudformation/apps/author-dispatcher.yaml
cloudformation/apps/chaos-monkey.yaml
cloudformation/apps/dns-records.yaml
cloudformation/apps/orchestrator.yaml
cloudformation/apps/publish-dispatcher.yaml
cloudformation/apps/publish.yaml
scripts/create-aem-stacks.sh

* Exported AutoScalingGroups for each of the groups
* Imported the Groups for the Chaos Monkey template to use them

Chaos Monkey ASG config

---

ansible/playbooks/apps/full-set/prerequisites.yaml

Added option region to first Ansible S3 task in prerequisites.yaml

Added option region to first ansible S3 task in prerequisites.yaml

---

examples/user-config/full-set/sandpit-apps-ami-ids.yaml

Added new AMI number of the fresh baked AMIs

Baked new example AMI for AEM6.2 and AEM6.3

---

ansible/library/delete_sdb_domain.py

This is a new Ansible module for deleting sdb domain when called in the computer-stacks.yaml  Playbook.

Ansible module-delete_sdb_domain

---

CHANGELOG.md
cloudformation/apps/aem/full-set/messaging.yaml

Add CW Alarm to monitor auto scaling messaging queue

---

ansible/playbooks/apps/aem/full-set/main.yaml

add new task "Delete Simian Army SimpleDB domain"

Update main.yaml with sdb-domain-deletion task

---

cloudformation/apps/aem/full-set/messaging.yaml

Subscription type hast to be a list. Fixed it.

Changed subscription endpoint to list

---

ansible/playbooks/apps/aem-stack-manager/main.yaml

Fixed syntax error in deletion section of the stack manager playbook.

Fixed syntax error in deleting section of stack manager

---

ansible/playbooks/apps/aem-stack-manager/main.yaml

Regarding https://github.com/shinesolutions/aem-aws-stack-builder/issues/97

modified s3 delete command to only the stackmanager s3 object

---

CHANGELOG.md
ansible/inventory/group_vars/apps.yaml
ansible/templates/stack-provisioner-hieradata.j2
examples/user-config/consolidated/sandpit-apps.yaml
examples/user-config/full-set/sandpit-apps.yaml

This allows any additional JVM OPTS parameters to be specified.

Add JVM_OPTS customizable parameter.

---

ansible/playbooks/apps/aem/full-set/prerequisites.yaml
cloudformation/apps/aem/full-set/instance-profiles-exports.yaml
cloudformation/apps/aem/full-set/main-c.yaml
cloudformation/apps/aem/full-set/prerequisites-c.yaml

Hi Cliff.
Please review .. I'm not 100% sure I have everything.

Permissions type c

---

ansible/playbooks/apps/aem/full-set/prerequisites.yaml
cloudformation/apps/aem/full-set/prerequisites-c.yaml

I'm an idiot .. can you please merge Cliff?

fix typo in ansible playbook

---

examples/descriptors/full-set/deploy-artifacts-descriptor.json
examples/descriptors/full-set/export-backup-descriptor.json
examples/user-config/consolidated/sandpit-apps.yaml
scripts/stack-init.sh

renamed post-common to action-scheduled-job

Update stack init to run action-scheduled-job manifest

---

CHANGELOG.md
cloudformation/apps/aem-stack-manager/instance-profiles.yaml
cloudformation/apps/aem-stack-manager/stack-manager.yaml

* Fix permission error for SnapshotPurge Lambda function
* Fix spelling error for StatusTopicPermission

Fix permission error for SnapshotPurge

---

scripts/update-snapshot-id-in-launch-conf.py

will be part of the fix for the issue #40

adding a script to update the snapshot id for a Launch configuration

---

CHANGELOG.md
ansible/inventory/group_vars/apps.yaml
ansible/templates/stack-provisioner-hieradata.j2
scripts/stack-init.sh

Add feature to configure logrotation per component and/or per instance.
Regarding issue https://github.com/shinesolutions/aem-aws-stack-builder/issues/12

Enhancement 12/logging improvement

---

ansible/inventory/group_vars/apps.yaml
ansible/templates/stack-provisioner-hieradata.j2

Add configuration for configure cron job content health check

Add configuration for configure cron job content health check

---

examples/user-config/apps/aem/consolidated.yaml

It would appear this is not required in examples.  Can you confirm that's the case?

Remove irrelevant snapshot features for Consolidated

---

ansible/inventory/group_vars/apps.yaml
docs/logs.md

Rename logrotation config and add logrotation for ssm commands.

Rename logrotation config and add logrotation for ssm commands.

---

CHANGELOG.md
cloudformation/apps/aem-stack-manager/ssm-commands/AEM-ManageService.yaml
cloudformation/apps/aem-stack-manager/ssm-commands/AEM-OfflineCompactionSnapshotConsolidated.yaml
cloudformation/apps/aem-stack-manager/ssm-commands/AEM-OfflineCompactionSnapshotFullset.yaml
cloudformation/apps/aem-stack-manager/ssm-commands/AEM-OfflineSnapshotConsolidated.yaml
cloudformation/apps/aem-stack-manager/ssm-commands/AEM-OfflineSnapshotFullset.yaml
cloudformation/apps/aem-stack-manager/ssm-commands/AEM-WaitUntilReady.yaml

Add output redirection in Cloudformation templates for SSM Commands Offline Snapshot & Offline Compaction Snapshot

Improved logging

---

CHANGELOG.md
ansible/inventory/group_vars/apps.yaml
ansible/templates/stack-provisioner-hieradata.j2
examples/user-config/apps/aem/consolidated.yaml
examples/user-config/apps/aem/full-set.yaml

Add new parameters to enable removing of old bak files in AEM repository

Add new parameters to enable removing of old bak files in AEM repository

---

CHANGELOG.md
ansible/inventory/group_vars/apps.yaml
ansible/templates/stack-provisioner-hieradata.j2
examples/user-config/apps/aem/full-set.yaml

* Add configuration parameters to enable random termination for each component except Author

Add configuration parameters to enable random termination

---

CHANGELOG.md
ansible/inventory/group_vars/apps.yaml
ansible/templates/stack-provisioner-hieradata.j2
docs/configuration.md
examples/user-config/apps/aem/consolidated.yaml
examples/user-config/apps/aem/full-set.yaml

* Add configuration parameters to configure wait until login page is ready during Stack Provisioning #184

Add configuration parameters for wait until login page is ready #184

---

CHANGELOG.md
ansible/inventory/group_vars/apps.yaml
ansible/templates/stack-provisioner-hieradata.j2
examples/user-config/apps/aem/consolidated.yaml
examples/user-config/apps/aem/full-set.yaml

* Add configuration parameters for configuring SAML authentication
* Add configuration parameters for configuring AEM Truststore

Add new configuration parameters for SAML

---

CHANGELOG.md
cloudformation/apps/aem-stack-manager/ssm-commands/AEM-OfflineCompactionSnapshotConsolidated.yaml
cloudformation/apps/aem-stack-manager/ssm-commands/AEM-OfflineSnapshotConsolidated.yaml

Update SSM Command for consolidated Offline-Snapshot & offline-compaction-snapshot to enable scheduling feature #182

Update SSM Commands for consolidated to enable snapshot scheduling #182

---

CHANGELOG.md
ansible/inventory/group_vars/all.yaml
ansible/templates/stack-provisioner-hieradata.j2
docs/configuration.md
examples/user-config/common/sandpit.yaml

Add new feature to configure AEM Apache http proxy configurator settings #235

Add new feature to configure AEM Apache http proxy settings #235

---

CHANGELOG.md
provisioners/ansible/playbooks/apps/aem-stack-manager/main.yaml
provisioners/ansible/playbooks/apps/aem-stack-manager/stack-data.yaml
provisioners/ansible/playbooks/apps/aem/stack-data.yaml
provisioners/ansible/playbooks/fetch-library.yaml

Fix path to staging dir in Ansible playbooks

Fix path to staging dir in Ansible playbooks

---

CHANGELOG.md
docs/faq.md

 Update FAQ 

---

CHANGELOG.md
scripts/stack-init.sh

Redirecting custom stack provisioner pre & post hook output to own 
logfile #298

Redirecting custom stack provisioner hooks output to own logfile #298

---

CHANGELOG.md
scripts/stack-init.sh

Suppress error `aws s3api head-object` stdout & stderr #48

Suppress error `aws s3api head-object` stdout & stderr #48

---

CHANGELOG.md
scripts/stack-init.sh

Added additional exit code checks to stack init process #294

Added additional exit code checks to stack init process #294

---

CHANGELOG.md
provisioners/ansible/library/stack_manager_config.py
provisioners/ansible/playbooks/apps/aem-stack-manager/main.yaml

Fixed error with generating stack manager config #302

Fixed error with generating stack manager config #302

---

CHANGELOG.md
templates/ansible/stack-provisioner-hieradata.j2

this change had been done to fix proxy_enabled issue for Shine solutions/stack provisioner#134

Shine solutions/stack provisioner#134

---

provisioners/ansible/playbooks/apps/aem-stack-manager/main.yaml
templates/cloudformation/apps/aem-stack-manager/main.yaml
templates/cloudformation/apps/aem-stack-manager/utilities.yaml

Fix Cloudwatch s3 stream permission issue

Fix Cloudwatch s3 stream permission issue

---

CHANGELOG.md
conf/ansible/inventory/group_vars/apps.yaml

Update default path for httpd logfile logrotation

Update default path for httpd logfile logrotation

---

templates/cloudformation/apps/aem/full-set/monitoring.yaml

Below Changes had been done :
1- Update Cloud watch arrangement
2- add numbers to the top of Dashboard and modify naming
3- divide graphs based on ELB types
4- Mix of Error Codes in the same graph

Update CloudWatch Dashboard

---

CHANGELOG.md
templates/cloudformation/apps/aem/full-set/monitoring.yaml

below changes had been done :
- Improved CloudWatch metrics
- Added ELB Metrics to CloudWatch Dashboard panel

Cloud watch

---

CHANGELOG.md
templates/ansible/stack-provisioner-hieradata.j2

Pass configuration `aem.enable_bak_files_cleanup` as boolean #341

Pass configuration `aem.enable_bak_files_cleanup` as boolean #341

---

CHANGELOG.md
templates/ansible/stack-provisioner-hieradata.j2
templates/cloudformation/apps/aem/full-set/monitoring.yaml

Updated CloudWatch Dashboard based on latest aws-scripts-mon configuration . 
- Customised Memory Added
- root and data Volume issue had been fixed

Change and Update CloudWatch Dashboard based on requirement

---

CHANGELOG.md
templates/ansible/stack-provisioner-hieradata.j2

1- Fix memory utilisation for all
2- add  missing metrics
3- change configuration based on customised CW put method "

4.1/CloudWatch Dashboard Fix

---

provisioners/ansible/playbooks/apps/aem/consolidated/switch-dns.yaml

https://github.com/shinesolutions/aem-opencloud-manager/issues/56

Fix the issue "swich consolidated dns record using author record"

---

CHANGELOG.md
templates/cloudformation/apps/aem/full-set/monitoring.yaml

- Changed data collection method for CloudWatch Dashboard (MemoryUtilization, Latency, ... )
- Fix Author Naming
- added JVM monitoring to CloudWatch Dashboard

CloudWatch Dashboard Fix and Update

---

CHANGELOG.md
docs/descriptors.md

Fixed documentation about the export-backups-descriptor

Fixed documentation about the export-backups-descriptor

---

CHANGELOG.md
templates/cloudformation/apps/aem/full-set/monitoring.yaml

below items had been changed :
- Changed data collection method for CloudWatch Dashboard (MemoryUtilization, Latency, ... )
- Fix Author Naming (Primary, Standby)
- added JVM monitoring to CloudWatch Dashboard

Fix CloudWatch (Master)

---

CHANGELOG.md
templates/cloudformation/apps/aem-stack-manager/stack-manager-c.yaml
templates/cloudformation/apps/aem-stack-manager/stack-manager.yaml

- Change AEM Stack Manager DynamoDB Billing mode from `PROVISIONED` to `PAY_PER_REQUEST` #356
- Increase AEM Stack Manager Lambda timeout from 15 seconds to 60 seconds #356

Changes in the AEM Stack Manager

---

CHANGELOG.md
provisioners/ansible/playbooks/apps/aem/full-set/main.yaml

Removed deletion of the deployment descriptor file for main stack 
deletion #358

#358 Removed deletion of the deployment descriptor file for main stack

---

CHANGELOG.md
provisioners/ansible/playbooks/apps/aem-stack-manager/stack-data.yaml
provisioners/ansible/playbooks/apps/aem/stack-data.yaml

Fix handle of the descriptor files #359

Fix 359/fix descriptor logic

---

CHANGELOG.md
templates/cloudformation/apps/aem/full-set/author-dispatcher.yaml
templates/cloudformation/apps/aem/full-set/author.yaml
templates/cloudformation/apps/aem/full-set/chaos-monkey.yaml
templates/cloudformation/apps/aem/full-set/orchestrator.yaml
templates/cloudformation/apps/aem/full-set/publish-dispatcher.yaml
templates/cloudformation/apps/aem/full-set/publish.yaml

Warining set to 60%
Critical set to 90%

Change CPU Utilization alarm Threshold as below

---

CHANGELOG.md
Makefile

Upgrade AEM Stack Manager Messenger to 2.11.0

Upgrade AEM Stack Manager Messenger to 2.11.0

---

CHANGELOG.md
templates/cloudformation/apps/aem-stack-manager/stack-manager-c.yaml
templates/cloudformation/apps/aem-stack-manager/stack-manager.yaml
templates/cloudformation/apps/aws-resources.yaml

- Add Tagging support to AEM Stack Manager DynamoDB
- Add Tagging support to AOC managed S3 Bucket

Extend AOC tagging.

---

CHANGELOG.md
templates/cloudformation/apps/aem/full-set/author-dispatcher.yaml
templates/cloudformation/apps/aem/full-set/author.yaml
templates/cloudformation/apps/aem/full-set/chaos-monkey.yaml
templates/cloudformation/apps/aem/full-set/orchestrator.yaml
templates/cloudformation/apps/aem/full-set/publish-dispatcher.yaml
templates/cloudformation/apps/aem/full-set/publish.yaml

Changed CPU utlisation statistic to maximum

aem-aws-stack-builder/CPU_Utilisation_modification#398

---

CHANGELOG.md
conf/ansible/inventory/group_vars/apps.yaml
docs/configuration.md
templates/ansible/stack-provisioner-hieradata.j2

- Add new configuration parameters `aem.[author|publish].run_modes` for 
configuring AEM run_modes
- Removed configuration parameters 
`reconfiguration.[author|publish].run_modes`

Add new configuration parameter for configuring AEM run_modes

---

CHANGELOG.md
provisioners/ansible/playbooks/apps/aem-stack-manager/main.yaml
provisioners/ansible/playbooks/apps/aem/consolidated/prerequisites.yaml
provisioners/ansible/playbooks/apps/aem/full-set/prerequisites.yaml

- Fixed Stack deletion process for **permission-type c** when AWS 
resource encryption via CMK is enabled [#407]

Fixed Stack deletion process for **permission-type c** [#407]

---

docs/faq.md

Update FAQ with information`s around the AEM Keystore

Update FAQ with information`s around the AEM Keystore

---

CHANGELOG.md
provisioners/ansible/playbooks/network/network.yaml

- Fix Network component playbook

Fix Network component playbook

---

CHANGELOG.md
conf/ansible/inventory/group_vars/apps.yaml

- Upgrade AEM Stack Manager Cloud to 1.9.0

Upgrade AEM Stack Manager Cloud

---

CHANGELOG.md
conf/ansible/inventory/group_vars/apps.yaml

- Upgrade AEM Orchestrator to 3.0.1

Upgrade AEM Orchestrator to 3.0.1

---

CHANGELOG.md
requirements.txt

Update Ansible to 3.0.0

---

CHANGELOG.md
requirements.txt

AWSCLI 1.19.8
Boto3 .17.8
Botocore 1.20.8

Changed below items version to make them consistent with PIP 21.0.1

---

templates/cloudformation/apps/aem/full-set/author-dispatcher.yaml
templates/cloudformation/apps/aem/full-set/author.yaml
templates/cloudformation/apps/aem/full-set/monitoring.yaml
templates/cloudformation/apps/aem/full-set/publish-dispatcher.yaml

Importing the Values of the target group and ALB to be used by the metrics.
Editing the metric definitions.
PradKhandelwal
19-08-2021

Updating cloudwatch dashboard metrics

---

CHANGELOG.md
templates/cloudformation/apps/aem-stack-manager/stack-manager-c.yaml
templates/cloudformation/apps/aem-stack-manager/stack-manager.yaml
templates/cloudformation/apps/aem-stack-manager/utilities.yaml

Upgrade Lambda runtime of AEM Stack Manager Lambda function to Python3.7 #455

Upgrade Lambda runtime of AEM Stack Manager Lambda function to Python3.7

---

CHANGELOG.md
templates/cloudformation/apps/aem/full-set/main-c.yaml

Fix Cloudformation template of permission type c

Fix Stack Creation for permission type c

---

CHANGELOG.md
templates/cloudformation/apps/aem/full-set/author-dispatcher.yaml
templates/cloudformation/apps/aem/full-set/author.yaml
templates/cloudformation/apps/aem/full-set/chaos-monkey.yaml
templates/cloudformation/apps/aem/full-set/orchestrator.yaml
templates/cloudformation/apps/aem/full-set/publish-dispatcher.yaml
templates/cloudformation/apps/aem/full-set/publish.yaml

- Update EC2 Userdata to wait until AWS S3 API can be accessed before proceeding with provisioning [#460]

Update EC2 Userdata to wait until AWS S3 API can be accessed

---

CHANGELOG.md
conf/ansible/inventory/group_vars/apps.yaml

Upgrade AEM AWS Stack Provisioner to 5.10.0

Upgrade AEM AWS Stack Provisioner to 5.10.0

---

CHANGELOG.md
templates/cloudformation/apps/aem/consolidated/main-c.yaml
templates/cloudformation/apps/aem/consolidated/main.yaml
templates/cloudformation/apps/aem/full-set/author-dispatcher.yaml
templates/cloudformation/apps/aem/full-set/author.yaml
templates/cloudformation/apps/aem/full-set/chaos-monkey.yaml
templates/cloudformation/apps/aem/full-set/orchestrator.yaml
templates/cloudformation/apps/aem/full-set/publish-dispatcher.yaml
templates/cloudformation/apps/aem/full-set/publish.yaml

- Update Consolidated EC2 Userdata to wait until AWS S3 API can be accessed before proceeding with provisioning [#460]
- Set AWS_DEFAULT_REGION in EC2 Userdata [#463]

Set AWS_DEFAULT_REGION in EC2 Userdata
