cloudformation/apps/author.yaml, cloudformation/apps/messaging.yaml
These two commits are applicable to separate issues. Due to Git confusion on my part I've ended up with both in one PR.
The changes to author.yaml are minor typo corrections related to issue #28 
The changes to messaging.yaml are the addition of a new CloudWatch alarm to address issue #70
=> Message queue alarm

CHANGELOG.md, ansible/inventory/group_vars/apps.yaml, ansible/templates/stack-provisioner-hieradata.j2
The first step to enable jmxremote on Author and Publisher instances to listen on a user defined port. 
https://github.com/shinesolutions/aem-aws-stack-provisioner/issues/51
=> Feature jmx enable to listen on user defined port

ansible/playbooks/apps/aem/full-set/prerequisites.yaml, cloudformation/apps/aem/full-set/messaging.yaml, cloudformation/apps/aem/full-set/prerequisites.yaml, examples/user-config/full-set/sandpit-apps.yaml
Extend Cloudformation & Ansible Template of the prerequisites messaging stack to enable E-Mail notification of CW Alarms to a pre-defined e-mail address. 
Regarding Issue#83
https://github.com/shinesolutions/aem-aws-stack-builder/issues/83
=> Added E-Mail notification for CW Alarms

cloudformation/apps/aem-stack-manager/instance-profiles.yaml
To enhance the logging and debugging of the SSM commands the fiels
need to be stored in a different place.
Regarding Issue https://github.com/shinesolutions/aem-stack-manager-messenger/issues/6
=> Modified S3 permissions for storing SSMOutput

cloudformation/apps/aem/consolidated/main-c.yaml
Simple addition to output the ip address of the consolidated instance so we can configure DNS further down the pipeline.
Please check the sanity before merging.
=> add outputs to the consolidated-c output

cloudformation/apps/aem-stack-manager/ssm-commands/AEM-PromoteAuthor.yaml
* update StackManager Event Promote Author standby instance to primary to call AWS Tool instead of AEM Tool
=> Update StackManager Event Promote Author standby to primary

ansible/inventory/group_vars/apps.yaml, ansible/library/stack_manager_config.py, ansible/templates/stack-provisioner-hieradata.j2, cloudformation/apps/aem-stack-manager/ssm-commands-cloudformation.yaml, cloudformation/apps/aem-stack-manager/ssm-commands/AEM-ScheduleOfflineSnapshot.yaml, examples/user-config/full-set/sandpit-apps.yaml, scripts/stack-init.sh
* Add Variable names to apps.yaml and example
* Add parameters to stack-provisioner-hieradata.j2 template
* Update stack-init to run pre-common & scheduled-jobs manifest
=> Add feature to configure scheduled aem jobs

examples/user-config/aem-stack-manager/sandpit-apps.yaml
Extend offline snapshot lifetime from 1 week to 364weeks = 7 years.
=> Extend offline snapshot lifetime.

ansible/inventory/group_vars/apps.yaml, examples/user-config/consolidated/sandpit-apps.yaml, examples/user-config/full-set/sandpit-apps.yaml
Regarding issue https://github.com/shinesolutions/puppet-aem-curator/issues/47
=> Add new oak version 1.6.6 for AEM 6.3.

examples/user-config/full-set/sandpit-apps.yaml
I believe this is a required prerequisite so it should be in examples.
=> Add required stack manager pair

requirements.txt
Simple fix to an issue which appears to have arisen due to ansible 2.6 release yesterday.
=> locking down python library versions in requirements.txt

requirements.txt
A recent update in AWS CLI has broken compatability with Ansible and botocore version that we have locked down.
For a customer this needs to be locked until they have the permissions revised in their aws accounts. Allowing them to use more recent versions of AEM OpenCloud.
=> locking down awscli to a specific value

templates/cloudformation/apps/aem/full-set/author.yaml, templates/cloudformation/apps/aem/full-set/chaos-monkey.yaml, templates/cloudformation/apps/aem/full-set/monitoring.yaml
Updated author stack and chaos-monkey to export output variable
Cloudwatch dashboard to display CPU, Memory, Disk, SQS, ELB metrics
=> Updated cloudwatch Dashboard for full set

provisioners/ansible/playbooks/fetch-library.yaml
Fix 'Unsupported proxy scheme: https. Currently ansible only supports  HTTP proxies'
Reference: https://stackoverflow.com/questions/46419260/error-in-ansible-2-3-2-unsupported-proxy-scheme-https?rq=1
=> Fix 'Unsupported proxy scheme: https. Currently ansible only supports  HTTP proxies'

CHANGELOG.md, conf/ansible/inventory/group_vars/apps.yaml, docs/configuration.md, templates/ansible/stack-provisioner-hieradata.j2
Add new parameters to define SSH public keys to deploy on the AEM Stack 
[#313]
Co-Authored-By: hoomaan-kh <hoomaan.kheirabadi@shinesolutions.com>
=> Add new parameters to define SSH public keys to deploy on the AEM Stack

CHANGELOG.md, templates/cloudformation/apps/aem/full-set/monitoring.yaml
Fixed syntax issue for Monitoring Cloudformation Stack template.
The `make config` was making this Cloudformation template unusuable. With this PR the `make config` does not make the cloudformation template unusable and will keep all the defined parameters.
=> Fixed syntax issue for Monitoring Cloudformation Stack template

CHANGELOG.md, templates/cloudformation/apps/aem-stack-manager/instance-profiles.yaml
Add new permissions for AEM Stack Manager to allow updating ASG scaling 
processes [#295].
This permission update is needed to allow the `aem_offline_snapshot.py` lambda function to update the ASG suspendes processes. 
This PR is needed by PR https://github.com/shinesolutions/aem-stack-manager-cloud/pull/41
=> Add new permissions for AEM Stack Manager [#295]

CHANGELOG.md, templates/cloudformation/apps/aem-stack-manager/utilities.yaml
Extend timeout for snapshot purge lambda function from 5 mins to 15 mins
=> Extend timeout for snapshot purge lambda function from 5 mins to 15 mins

CHANGELOG.md, conf/ansible/inventory/group_vars/apps.yaml, docs/configuration.md, docs/faq.md, docs/upgrade-guide.md, templates/ansible/stack-provisioner-hieradata.j2
Update configura
- Added to FAQ to explain why the admin user password change can fail
- Added to FAQ to explain why the system user configuration parameters changed #352
- Add new configuration parameters `system_users.[author|publish].[admin|deployer|exporter|importer|orchestrator|replicator].[name|path]` #352
- Add new hiera parameter `author::aem_system_users` & `publish::aem_system_users` #352
- configuration parameter `system_users.[author|publish].admin.path` (previously known as `system_users.admin.path`) is now a *mandatory* parameter
- Removed configuration parameters `system_users.[admin|deployer|exporter|importer|orchestrator|replicator]` #352
- Removed hiera parameter `common::aem_system_users` #352
=> Update AEM System users configuration parameters

CHANGELOG.md, conf/ansible/inventory/group_vars/all.yaml, docs/configuration.md, provisioners/ansible/playbooks/apps/aem/consolidated/main.yaml, provisioners/ansible/playbooks/apps/aem/full-set/main.yaml
Add feature to enable removal of all available Cloudwatch Loggroups 
while deleting an AEM Stack [#366]
=> feat(#366): add feature to remove all available Cloudwatch Loggroups

CHANGELOG.md, templates/cloudformation/apps/aem/full-set/author-dispatcher.yaml, templates/cloudformation/apps/aem/full-set/author.yaml, templates/cloudformation/apps/aem/full-set/chaos-monkey.yaml, templates/cloudformation/apps/aem/full-set/messaging.yaml, templates/cloudformation/apps/aem/full-set/orchestrator.yaml, templates/cloudformation/apps/aem/full-set/publish-dispatcher.yaml
Old SNS Topic had been completely remove and  new warning and  critical topics will be used.
=> migrate Old SNS topic

CHANGELOG.md, provisioners/ansible/playbooks/apps/aem/consolidated/switch-dns.yaml, requirements.txt
1. Add boto library, which is required for the Ansible switch dns module
2. Update boto3 and botocore verison to fix incompatible pip installation error
=> Fix for switch dns failure

CHANGELOG.md, templates/cloudformation/apps/aem/full-set/prerequisites-c.yaml
- Add missing CF Stack output parameter for full-set permission type c 
[#378]
=> [#378] Add missing Stack output parameter for full-set permission type c

CHANGELOG.md, scripts/stack-init.sh
Add `aws_region` support for `stack-init` script 
shinesolutions/aem-opencloud-manager#65
=> Add support `aws_region` support to stack-`init` script

CHANGELOG.md, scripts/stack-init.sh
This PR will add two additional steps to the stack-init process:
1. Change dir to the custom-stack-provisioner dir before the execution of the custom-stack-provisioner
2. Change dir back to the aem-aws-stack-provisioner dir after the exeuction of the custom-stack-provisioner
This is necessary because the user is expecting to be in the directory of the custom-stack-provisioner when the custom-stack-provisioner gets executed and therefore the user can use regular mechanisms to determine the path of the current dir.
=> Update stack-init script to change dir to custom-stack-provisioner path

CHANGELOG.md, templates/cloudformation/apps/aem-stack-manager/ssm-commands/AEM-DeployArtifacts.yaml, templates/cloudformation/apps/aem-stack-manager/ssm-commands/AEM-ExportPackage.yaml, templates/cloudformation/apps/aem-stack-manager/ssm-commands/AEM-ExportPackages.yaml, templates/cloudformation/apps/aem-stack-manager/ssm-commands/AEM-ImportPackage.yaml, templates/cloudformation/apps/aem-stack-manager/ssm-commands/AEM-RunAemUpgrade.yaml
Increase SSM Document `RunAEMUpgrade` default sleep timer to `1200` 
seconds [#401]
=> Increase SSM Document `RunAEMUpgrade` default sleep timer to `1200`

CHANGELOG.md, conf/ansible/inventory/group_vars/apps.yaml, docs/configuration.md, templates/cloudformation/apps/aem/full-set/author-dispatcher.yaml, templates/cloudformation/apps/aem/full-set/author.yaml, templates/cloudformation/apps/aem/full-set/publish-dispatcher.yaml
- Changed default parameter `compute.elb_cipher_suite` to 
`AOCELBSecurityPolicy-TLS-1-2-2017-01`
- Disable TLS 1.0 & TLS 1.1 support for Author-Dispatcher, 
Publish-Dispatcher & Author ELB
=> Add custom CIPHER to Full-Set ELB to disable insecure SSL Protocols

templates/ansible/stack-provisioner-hieradata.j2
Resolves RS-71 where replication agent protocol and port were not being passed to stack provisioner from config.
=> Corrects replication agent parameter structure in hieradata

CHANGELOG.md, templates/cloudformation/apps/aem-stack-manager/stack-manager-c.yaml, templates/cloudformation/apps/aem-stack-manager/stack-manager.yaml, templates/cloudformation/apps/aem-stack-manager/utilities.yaml
Python runtime v3.7 is set to deprecate in Nov'2023. Thus, this PR upgrades the Python3.7 lambdas to Python3.8 runtime.
For more info on to-be-deprecated runtimes https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
=> Update lambdas runtime version to python3.8
